import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.className} bg-white text-black dark:bg-gray-900 dark:text-white`}>
        <div className={'p-4 max-w-[1216px] w-full m-auto'}>
            <ThemeProvider attribute='class' defaultTheme='system'>
                <Navbar/>
                {children}
                <Footer/>
            </ThemeProvider>
        </div>
        </body>
        </html>
    );
}
