export const metadata = {
    title: "Personal Blog | Home",
    description: "Generated by create next app",
};

export default function Home() {
    return (
        <div>
            <div className={'min-h-[60vh] flex items-center px-8 lg:px-0'}>
                <h1 className={'text-indigo-600 uppercase font-[700] text-[50px] md:text-[76px] leading-[92px]'}>
                    The Blog - <br/> Personal <br/> Blog
                </h1>
            </div>
        </div>
    );
}
